apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp_s1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp_s1
  template:
    metadata:
      labels:
        app: nodeapp_s1 
    spec:
      containers:
      - name: nodeserver
        image: akterd/testsuper30:devops-integration_v2
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp_s1 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
